language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
before_script:
  - ls
  - cd spec/dummy
  - ls
  - bundle exec rake db:test:prepare
  - cd ../..
  - ls
rvm:
  - 2.0.0
  - 2.1.0
script:
  - RAILS_ENV=test bundle exec rspec
gemfile:
  - Gemfile
